In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("pandasEDACleaning.ipynb")

## Lecture Section

In this lecture, we will cover more of the `pandas` library.
Specifically:

* Cleaning Data
    * Replacing `None` values
    * Changing data types/formats
    * Removing duplicate rows
* Exploratory Data Analysis
    * Finding mean, median, mode of a column
    * Summarizing the data
    * Correlations

We will be working with the synthetic (not-real-world data) below.

In [2]:
import pandas as pd
df = pd.read_csv('data/synthetic_data.csv')
df.head()

   ID   Name    Status   Score      JoinDate
0  30  Alice       NaN   98.59  '02-18-2023'
1  14  Diana   Pending  120.09  '12-26-2023'
2  18  Diana  Inactive   58.26  '11-05-2023'
3  10   Hank   Pending   72.49  '08-03-2023'
4   7  Frank    Active   71.26  '01-21-2023'

First, we want to see the general information about our dataset. Use `.info()` to do this in the code block below.

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        54 non-null     int64
 1   Name      54 non-null     str
 2   Status    42 non-null     str
 3   Score     50 non-null     float64
 4   JoinDate  54 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 2.2 KB

Take note of how many rows there are in the dataset. Which columns have missing data? Are any of the columns the wrong type?

### Cleaning

Let's handle the missing data first. We have three options. We can remove the rows that have missing data, fill in the missing data with a different value, or we can fill in the missing data with a different value depending on the column of the missing data.

**Drop rows with missing data**

Replace the `XXX` with the `.dropna()` method.

In [20]:
dropped_rows = df.dropna()
dropped_rows.info()

<class 'pandas.DataFrame'>
Index: 34 entries, 1 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          34 non-null     int64
 1   Name        34 non-null     str
 2   Status      34 non-null     str
 3   Score       34 non-null     float64
 4   JoinDate    34 non-null     datetime64[us]
 5   Status_Num  34 non-null     float64
dtypes: datetime64[us](1), float64(2), int64(1), str(2)
memory usage: 1.9 KB

**Changing all missing data to some value**

Replace the `XXX` with the `.fillna()` method. Pass 130 as the argument.

In [24]:
df_replaced_130 = df.fillna(130)
df_replaced_130.info()

<class 'pandas.DataFrame'>
Index: 50 entries, 0 to 53
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          50 non-null     int64
 1   Name        50 non-null     str
 2   Status      50 non-null     object
 3   Score       50 non-null     float64
 4   JoinDate    50 non-null     datetime64[us]
 5   Status_Num  50 non-null     float64
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(1)
memory usage: 2.7+ KB

In [25]:
df_replaced_130.head()

   ID   Name    Status   Score   JoinDate  Status_Num
0  30  Alice       130   98.59 2023-02-18       130.0
1  14  Diana   Pending  100.00 2023-12-26         0.0
2  18  Diana  Inactive   58.26 2023-11-05         2.0
3  10   Hank   Pending   72.49 2023-08-03         0.0
4   7  Frank    Active   71.26 2023-01-21         3.0

**Change missing values to some value based on column**

In [7]:
df_new_stat = df.fillna({"Status": 'Missing'}) # replace NAs with a blanket value
df_new_stat.head()

   ID   Name    Status   Score      JoinDate
0  30  Alice   Missing   98.59  '02-18-2023'
1  14  Diana   Pending  120.09  '12-26-2023'
2  18  Diana  Inactive   58.26  '11-05-2023'
3  10   Hank   Pending   72.49  '08-03-2023'
4   7  Frank    Active   71.26  '01-21-2023'

In [8]:
df_new_stat.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        54 non-null     int64
 1   Name      54 non-null     str
 2   Status    54 non-null     str
 3   Score     50 non-null     float64
 4   JoinDate  54 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 2.2 KB

In [9]:
df_new_stat.fillna({"Score":df['Score'].mean()}, inplace=True) # replace it with the average of column
df_new_stat.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        54 non-null     int64
 1   Name      54 non-null     str
 2   Status    54 non-null     str
 3   Score     54 non-null     float64
 4   JoinDate  54 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 2.2 KB

To find the median or mode, we can use `.median()` and `.mode()`.

Now we want to fix the JoinDate column. Some of the entries don't look like dates, so we will use `.to_datetime()` to fix that.

In [10]:
df['JoinDate'] = pd.to_datetime(df['JoinDate'].str.strip("'"))
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        54 non-null     int64
 1   Name      54 non-null     str
 2   Status    42 non-null     str
 3   Score     50 non-null     float64
 4   JoinDate  54 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 2.2 KB

In [11]:
df.head()

   ID   Name    Status   Score   JoinDate
0  30  Alice       NaN   98.59 2023-02-18
1  14  Diana   Pending  120.09 2023-12-26
2  18  Diana  Inactive   58.26 2023-11-05
3  10   Hank   Pending   72.49 2023-08-03
4   7  Frank    Active   71.26 2023-01-21

What if we know a value is wrong? For example, row 1 has a score of 120.9, but all other rows have scores between 0 and 100.

In [12]:
df.loc[1, "Score"] = 100 # change single value
df.head()

   ID   Name    Status   Score   JoinDate
0  30  Alice       NaN   98.59 2023-02-18
1  14  Diana   Pending  100.00 2023-12-26
2  18  Diana  Inactive   58.26 2023-11-05
3  10   Hank   Pending   72.49 2023-08-03
4   7  Frank    Active   71.26 2023-01-21

We can change it one-by-one like above, or we can make a rule and change multiple rows at once.

In [13]:
for x in df.index:
    if df.loc[x, "Score"] > 100:
        df.loc[x, "Score"] = 100

df.head()

   ID   Name    Status   Score   JoinDate
0  30  Alice       NaN   98.59 2023-02-18
1  14  Diana   Pending  100.00 2023-12-26
2  18  Diana  Inactive   58.26 2023-11-05
3  10   Hank   Pending   72.49 2023-08-03
4   7  Frank    Active   71.26 2023-01-21

Another option is to use `.drop(index)` and remove the row with the wrong data.

Finally, let's check for duplicated rows using `.duplicated()`. Try it in the code block below. How many rows are duplicated?

In [14]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38     True
39     True
40    False
41    False
42    False
43     True
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51     True
52    False
53    False
dtype: bool

We can remove the duplicated rows with `drop_duplicates()`

In [15]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 50 entries, 0 to 53
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        50 non-null     int64
 1   Name      50 non-null     str
 2   Status    38 non-null     str
 3   Score     46 non-null     float64
 4   JoinDate  50 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 2.3 KB

### Exploratory Data Analysis

We have already covered some aspects of EDA. For example, `.info()` tells us how many rows we have, of what types, and how many NA values exist within each of our columns. We also used `.mean()` a few moments ago, and we can use `.mode()` and `.median()` in a similar way.

In [16]:
print(df['Score'].mean())
print(df['Score'].mode(0)) #NaN because there are no duplicates
                        # 0 means by column, 1 by row
print(df['Score'].median())

73.45586956521738
0   NaN
Name: Score, dtype: float64
72.66

We will continue to introduce aspects of EDA in Python throughout other lectures. However, we will introduce one more function now: `corr()`. `corr()` returns a correlation matrix of the *features in your dataframe.

* features are also known as your independant variables, or x's.

`corr()` only works with numeric columns. Since we only have Score, we could convert Status to a numeric mapping and run `corr()`

In [18]:
status_map = {
    'Pending': 0,
    'Missing': 1,
    'Inactive': 2,
    'Active': 3
}

df['Status_Num'] = df['Status'].map(status_map)
new_df = df[['Status_Num', 'Score']]
correlation = new_df.corr()
print(correlation)

            Status_Num    Score
Status_Num     1.00000  0.03114
Score          0.03114  1.00000

Another option is to create `dummy` variables out of Status. This will give us a correlation between each Status and the Score variable.

In [19]:
dummies = pd.get_dummies(df['Status'], prefix='Status')
new_df = pd.concat([dummies, df['Score']], axis=1)
correlation_matrix = new_df.corr()
print(correlation_matrix['Score'].drop('Score'))

Status_Active     -0.048630
Status_Inactive   -0.040463
Status_Pending    -0.084115
Name: Score, dtype: float64

We can tell from both that there is not much of a correlation to be found, because the synthetic data was created randomly.

In a future lecture, we will see how to turn the correlations into heatmaps.

## Assignment Section

**Question 1.**

We will borrow a dataset from Kaggle for this exercise. I have edited it for the purposes of this course.
https://www.kaggle.com/datasets/msjahid/colorado-motor-vehicle-sales-data

For this problem, you will use `pandas` to read the `"data/colorado_motor_vehicle_sales.csv"` file.
The dataset has missing information:
* Replace null data in the `sales` column with `0`.
* If the country is "xxx", replace it with "NA".

In [49]:
import pandas as pd
# Reading the CSV file
df = pd.read_csv('data/colorado_motor_vehicle_sales.csv')

# Replacing the null data in the 'sales' column with 0
df.fillna({"sales": 0})


# Replacing 'xxx' in the 'country' column with 'NA'
for x in df.index:
 if df.loc[x, "county"] == "xxx":
     df.loc[x,"county"] = "NA"

# Displaying the first few rows of the dataset to verify the changes
df.head()

   year  quarter              county        sales
0  2008        1               Adams  231609000.0
1  2008        1            Arapahoe  550378000.0
2  2008        1  Boulder/Broomfield  176771000.0
3  2008        1              Denver  200103000.0
4  2008        1             Douglas   93259000.0

In [50]:
grader.check("q1")

q1 results: All test cases passed!

**Question 2.**
Using the same dataframe from Question 1, change the `0`s in the `sales` column to the mean of the `sales` column.

In [51]:
import pandas as pd

# Read the CSV file (if not already loaded)
df = pd.read_csv("data/colorado_motor_vehicle_sales.csv")

m = df["sales"].mean()

for x in df.index:
 if df.loc[x, "sales"] == 0:
     df.loc[x,"sales"] = m

# Calculating the mean excluding zeros
mean_excluding_zeros = df[df['sales'] == 0]['sales'].mean()

# Replacing the  0s in the sales column with the mean
df.loc[df['sales'] == 0, 'sales'] = mean_excluding_zeros

df.head()

   year  quarter              county        sales
0  2008        1               Adams  231609000.0
1  2008        1            Arapahoe  550378000.0
2  2008        1  Boulder/Broomfield  176771000.0
3  2008        1              Denver  200103000.0
4  2008        1             Douglas   93259000.0

In [52]:
grader.check("q2")

q2 results: All test cases passed!

**Question 3.**

Using the same dataframe as Question2:
* Find the correlation between quarter and sales and save the matrix in `correlation_quarter`
* Find the correlation between year and sales and save the matrix in `correlation_year`
* Using the example in the lecture, create a dummy variable of `year` (use `prefix = "q"`), then find the correlation between the dummy variable and `sales`. Save the output to `correlation_matrix`.

In [56]:
import pandas as pd
import numpy as np

# Finding the correlation between quarter and sales
correlation_quarter = df[['quarter', 'sales']].corr()
print("Correlation between quarter and sales:")
print(correlation_quarter)

# Finding the correlation between year and sales
correlation_year = df[['year', 'sales']].corr()
print("Correlation between year and sales:")
print(correlation_year)


# Creating dummy variables for year with the prefix "q"
dummies = pd.get_dummies(df['year'], prefix='q')
# Adding the dummy variables to the dataframe
new_df_quart_sep = pd.concat([df, dummies], axis=1)
# Finding the correlation between the dummy variables and sales
dummy_columns = dummies.columns.tolist()
# Select only the dummy columns and sales# Select only the dummy columns and sales
columns_for_correlation = dummy_columns + ['sales']
correlation_matrix = new_df_quart_sep[columns_for_correlation].corr()
print(correlation_matrix['sales'])

Correlation between quarter and sales:
          quarter     sales
quarter  1.000000  0.034802
sales    0.034802  1.000000
Correlation between year and sales:
           year     sales
year   1.000000  0.169835
sales  0.169835  1.000000
q_2008   -0.030782
q_2009   -0.112186
q_2010   -0.095789
q_2011    0.038025
q_2012   -0.027125
q_2013    0.023606
q_2014    0.071376
q_2015    0.128796
sales     1.000000
Name: sales, dtype: float64

In [57]:
grader.check("q3")

q3 results: All test cases passed!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [55]:
grader.check_all()

q1 results:
    q1 - 1 result:
        ❌ Test case failed
        Trying:
            assert 'xxx' not in df['county'].values
        Expecting nothing
        **********************************************************************
        Line 1, in q1 0
        Failed example:
            assert 'xxx' not in df['county'].values
        Exception raised:
            Traceback (most recent call last):
              File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.3312.0_x64__qbz5n2kfra8p0\Lib\doctest.py", line 1398, in __run
                exec(compile(example.source, filename, "single",
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             compileflags, True), test.globs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<doctest q1 0[0]>", line 1, in <module>
                assert 'xxx' not in df['county'].values
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            AssertionError

    q1 - 2 result:
        ✅ Test case passed

q2 results: All test cases passed!

q3 results: All test cases passed!